/* config.h.in — generated by CMake */

/* Define if you have specific functions or headers */
#cmakedefine HAVE_STRLCPY @HAVE_STRLCPY@
#cmakedefine HAVE_STRLCAT @HAVE_STRLCAT@
#cmakedefine HAVE_MEMCHR @HAVE_MEMCHR@
#cmakedefine HAVE_MEMSET @HAVE_MEMSET@
#cmakedefine HAVE_GETLINE @HAVE_GETLINE@
#cmakedefine HAVE_VIS @HAVE_VIS@
#cmakedefine HAVE_UNVIS @HAVE_UNVIS@
#cmakedefine HAVE_ISSETUGID @HAVE_ISSETUGID@
#cmakedefine HAVE_ENDPWENT @HAVE_ENDPWENT@
#cmakedefine HAVE_GETPW_R_POSIX @HAVE_GETPW_R_POSIX@
#cmakedefine HAVE_ISASCII @HAVE_ISASCII@
#cmakedefine HAVE_SECURE_GETENV @HAVE_SECURE_GETENV@

#cmakedefine HAVE_STDINT_H @HAVE_STDINT_H@
#cmakedefine HAVE_WCHAR_H @HAVE_WCHAR_H@
#cmakedefine HAVE_DIRENT_H @HAVE_DIRENT_H@
#cmakedefine HAVE_DLFCN_H @HAVE_DLFCN_H@
#cmakedefine HAVE_FCNTL_H @HAVE_FCNTL_H@
#cmakedefine HAVE_LIMITS_H @HAVE_LIMITS_H@
#cmakedefine HAVE_NCURSES_H @HAVE_NCURSES_H@
#cmakedefine HAVE_CURSES_H @HAVE_CURSES_H@
#cmakedefine HAVE_TERMCAP_H @HAVE_TERMCAP_H@
#cmakedefine HAVE_TERM_H @HAVE_TERM_H@
#cmakedefine HAVE_SYS_WAIT_H @HAVE_SYS_WAIT_H@
#cmakedefine HAVE_PWD_H @HAVE_PWD_H@
#cmakedefine HAVE_IOCTL_H @HAVE_IOCTL_H@

/* Define if building on Windows */
#cmakedefine _WIN32 @WIN32@

/* Define version string */
#define LIBEDIT_VERSION "@LT_VERSION@"

/* Prevent redeclarations of standard C functions on Windows */
#ifdef _MSC_VER
# define _CRT_SECURE_NO_WARNINGS
# define _CRT_NONSTDC_NO_WARNINGS
#endif

#if defined(_MSC_VER) || defined(__MINGW64__)
#define __WINDOWS__ 1
#endif

#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 1
#endif
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
#ifndef _DARWIN_C_SOURCE
# define _DARWIN_C_SOURCE 1
#endif

#include "sys.h"

#ifdef __WINDOWS__
#define __STDC_ISO_10646__ 1
#define HAVE_NCURSES_H 1
#endif
